<a href="https://colab.research.google.com/github/Dhatri3/sms-spam-detector/blob/main/SMS_Spam_Detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

df = pd.read_csv(url, sep="\t", header=None, names=["label", "message"])

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
X=df["message"]
y=df["label"]
print(X.head())
print(y.head())

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object
0     ham
1     ham
2    spam
3     ham
4     ham
Name: label, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
X_tfidf=vectorizer.fit_transform(X)
print("original messages:",X.shape)
print("Numerical data:",X_tfidf.shape)

original messages: (5572,)
Numerical data: (5572, 8713)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X_tfidf,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 4457
Testing samples: 1115

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

print("Model trained successfully! ")

Model trained successfully! 🎉

In [ ]:
y_pred = model.predict(X_test)

print(y_pred[:10])

['ham' 'ham' 'ham' 'spam' 'ham' 'ham' 'ham' 'ham' 'ham' 'ham']

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9605381165919282

Classification Report:
              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       966
        spam       1.00      0.70      0.83       149

    accuracy                           0.96      1115
   macro avg       0.98      0.85      0.90      1115
weighted avg       0.96      0.96      0.96      1115

Confusion Matrix:
[[966   0]
 [ 44 105]]

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

In [ ]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[966   0]
 [ 44 105]]

In [ ]:
message = ["Congratulations! You have won a free prize. Call now to claim it!"]

message_tfidf = vectorizer.transform(message)

prediction = model.predict(message_tfidf)

print("Message:", message[0])
print("Prediction:", prediction[0])

Message: Congratulations! You have won a free prize. Call now to claim it!
Prediction: spam

In [ ]:
message = ["Hey, are you coming to college tomorrow?"]

message_tfidf = vectorizer.transform(message)

prediction = model.predict(message_tfidf)

print("Message:", message[0])
print("Prediction:", prediction[0])

Message: Hey, are you coming to college tomorrow?
Prediction: ham

In [ ]:
def predict_spam(message):
    message_tfidf = vectorizer.transform([message])
    prediction = model.predict(message_tfidf)[0]

    if prediction == "spam":
        return " SPAM"
    else:
        return " NOT SPAM"


print(predict_spam("Congratulations! You won 10 lakh rupees. Click now!"))
print(predict_spam("Hey, I'll call you after class."))

✅ NOT SPAM
✅ NOT SPAM